version: '3.8'

services:
  todo-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
    volumes:
      - todo_data:/app/prisma
    restart: unless-stopped

volumes:
  todo_data:
